eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern:
    level: %5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
